// Copyright 2023 ktiays
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

pub const LIPSUM_CONTENTS: [&str; 15] = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra porta elementum. Mauris sit amet eleifend nisl, vitae tempus elit. Nulla facilisi. Pellentesque eget consectetur tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi facilisis volutpat enim. Duis ante lectus, finibus a dolor non, fringilla aliquet felis. Ut pellentesque tellus vel nisl elementum sollicitudin. Nullam non tempor orci, luctus hendrerit lorem. Aliquam mattis erat vulputate tincidunt condimentum. Integer justo lectus, fermentum et velit in, dictum eleifend massa. Maecenas porttitor vulputate mollis.", 
    "Vestibulum erat ex, accumsan malesuada dignissim eget, convallis nec nunc. Proin maximus, purus id suscipit ornare, mi ligula euismod erat, sit amet blandit lacus purus vitae elit. Nullam fringilla sagittis tortor, non tristique ex commodo ut. Morbi lobortis ornare mi quis faucibus. Vestibulum sit amet justo non arcu ullamcorper facilisis. Proin lobortis, purus vitae aliquet porta, orci lacus ultricies mi, vitae gravida odio mauris eget sapien. Vivamus ut ultricies nibh, eget tempus libero. Quisque lacinia at nibh eget tincidunt. Donec non nunc ut quam ultricies vulputate at sit amet purus. Curabitur non porta purus, at maximus nibh.",
    "Quisque tincidunt, libero id dictum volutpat, leo turpis scelerisque nulla, et pretium odio nibh ut massa. Morbi lorem turpis, facilisis sit amet est non, tempor facilisis arcu. Nam rhoncus pharetra bibendum. Sed mattis ipsum magna, sit amet rutrum sapien lobortis at. Pellentesque quam felis, convallis nec libero ac, congue tincidunt augue. Fusce at leo dolor. Proin efficitur rutrum nisi a pretium. Maecenas ac turpis lectus. Morbi sed sapien eget lorem finibus fermentum. Suspendisse vitae porttitor mauris.",
    "Vestibulum blandit sollicitudin tortor ut pretium. Donec dapibus varius feugiat. Nam in nulla lacus. Sed eget varius nisl. Proin maximus risus a ligula accumsan feugiat. Duis tempus mattis vulputate. Aenean ornare nunc eu ligula vestibulum congue in quis nulla.",
    "Sed sit amet lorem gravida, auctor felis facilisis, tristique leo. Proin ut neque laoreet, fermentum nibh pulvinar, condimentum lectus. Quisque ut interdum ante. Donec posuere elit lectus. Vestibulum congue nisi sed libero ullamcorper, finibus bibendum lectus eleifend. Etiam sed justo felis. Duis ultrices ornare ornare. Proin ultricies ipsum quis leo ornare, vel aliquam lacus condimentum. Nullam tempus, felis vitae dictum vehicula, velit erat blandit est, in fermentum lacus lacus vitae risus. Sed nec mi eros. Nulla convallis odio in justo feugiat, non maximus tortor iaculis. Mauris gravida tortor id euismod finibus. Curabitur consequat eu dolor in ornare. Praesent id blandit lectus.",
    "Proin ipsum leo, pellentesque nec feugiat sed, pulvinar et tortor. Sed suscipit, quam in tristique aliquet, magna orci cursus enim, sit amet tincidunt dolor ante et elit. Quisque at venenatis diam. Vestibulum sed egestas diam. Maecenas rhoncus magna nec lacus feugiat, id tempus diam scelerisque. Curabitur at tellus mollis, vulputate urna in, lobortis ipsum. Maecenas diam turpis, maximus ut dictum eget, varius ac est. Cras pellentesque libero vel massa facilisis, nec bibendum lorem luctus. Proin suscipit metus mauris, at pellentesque mi ullamcorper eget. Phasellus dignissim ex in sollicitudin dapibus.",
    "Cras at turpis et nibh feugiat sodales quis et mi. Phasellus mollis massa at tortor aliquam, sit amet pharetra ante bibendum. Vestibulum dictum egestas vehicula. Praesent turpis nisi, molestie quis erat id, commodo commodo elit. Nunc feugiat odio eu ipsum accumsan, fermentum iaculis tortor pretium. Nulla pretium sit amet est quis euismod. Quisque id ligula vestibulum, semper enim vel, placerat magna. Aenean eget leo ut nisi vulputate convallis. In sagittis dolor eget posuere porta. Mauris sapien erat, pellentesque eget nulla a, sodales tincidunt nibh.",
    "Proin eleifend felis nec metus eleifend viverra. Curabitur porttitor nulla risus, a tincidunt neque laoreet egestas. Fusce rhoncus sollicitudin massa vitae luctus. Etiam est urna, pretium at ex at, luctus posuere nisi. Morbi tempor condimentum nibh, in imperdiet urna dignissim quis. Sed ut finibus turpis. Fusce iaculis arcu urna, elementum interdum nibh sollicitudin vel. Nulla turpis tellus, tincidunt consectetur posuere a, blandit in massa. Phasellus viverra id arcu vitae pharetra.",
    "Aenean sagittis gravida lorem, sit amet gravida velit facilisis sed. Nulla quis massa semper, faucibus turpis in, iaculis ante. Sed faucibus ultricies aliquam. Donec eu erat nulla. Mauris placerat aliquam nisl consectetur congue. Nam vitae convallis magna. Nam at faucibus nisl.",
    "Aliquam erat volutpat. Aenean egestas justo a diam tincidunt, ut auctor mi vulputate. Integer sit amet egestas nibh. Quisque fermentum mollis eros pellentesque posuere. In ut gravida purus, non hendrerit neque. Aliquam efficitur mollis sem, in dictum felis consequat mollis. Quisque ut congue metus. Duis hendrerit posuere turpis quis maximus. Fusce in suscipit erat. Sed at congue justo. Phasellus sed turpis pharetra, cursus neque ac, euismod eros.",
    "Aenean dolor diam, hendrerit vitae fermentum dignissim, tempus quis nisl. Suspendisse id nibh ac orci pharetra faucibus a nec tellus. Nulla interdum laoreet tempus. Maecenas magna lorem, imperdiet in tristique quis, vestibulum non ex. Cras eu rutrum nibh, id varius orci. Maecenas tempor odio quis nulla pharetra, a posuere ligula iaculis. Mauris sagittis ultricies diam, a tristique orci consequat eget. Integer facilisis commodo dui, malesuada condimentum urna malesuada a. Duis auctor nisi et mattis tempor. Nullam a scelerisque neque.",
    "Sed eu ante at mi pretium euismod at non arcu. Curabitur rhoncus porta tincidunt. Cras ut mattis nunc. Fusce elementum viverra odio, in placerat orci accumsan ut. Donec dapibus in lectus ac commodo. Ut luctus, odio nec tincidunt egestas, mauris leo blandit ligula, non ultricies massa lacus nec tortor. Maecenas finibus felis eu fringilla vulputate. Nulla gravida tempor sodales. Quisque ut rhoncus orci, id bibendum turpis. Morbi et luctus felis. Phasellus vel purus facilisis, tempus ex non, blandit ipsum. Nullam interdum lacus a finibus interdum. Nulla facilisi. Sed erat diam, sagittis ac ipsum sed, posuere sollicitudin ex.",
    "Duis molestie vestibulum erat nec sollicitudin. Nulla aliquam, tortor id scelerisque iaculis, ipsum risus efficitur lacus, sed sollicitudin eros nunc eu urna. Sed porta semper sem, eget ullamcorper velit aliquet fringilla. Vivamus sit amet consequat odio. Integer feugiat vehicula vehicula. Integer egestas eros vestibulum, faucibus massa eget, blandit risus. Donec in mauris in diam placerat vestibulum.",
    "Cras sed massa diam. Etiam fermentum justo non eros tempor rhoncus. Cras volutpat felis quis quam molestie venenatis. Quisque bibendum rhoncus pulvinar. Nullam mi tortor, dignissim eu ligula a, lacinia finibus mi. Praesent id tellus accumsan, bibendum diam in, tincidunt ipsum. Integer nec ullamcorper ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Fusce non nulla mauris. Aliquam pharetra, ex ut elementum venenatis, mi eros egestas mauris, id molestie tortor enim sollicitudin nunc.",
    "Cras accumsan felis diam, ac bibendum arcu volutpat et. Aenean diam justo, hendrerit et interdum vel, dictum nec massa. Nunc tincidunt sit amet dui eu mattis. Vestibulum accumsan ex non massa varius, a malesuada est rutrum. Donec et lorem ornare, tristique felis in, sagittis urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque luctus, leo vel accumsan dapibus, tellus elit lobortis neque, et volutpat eros sem sed risus. Sed elementum et odio id pretium. Nunc molestie dolor massa. In hac habitasse platea dictumst. Praesent eu mauris sodales, cursus tortor sit amet, lobortis tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc maximus posuere nisi, at tempor nisi dapibus sagittis. Phasellus scelerisque sem nulla, vel porta nunc hendrerit id.",
];
