[package]
name = "scroll-physics"
authors = ["ktiays <cuansky@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
