[package]
name = "fluid-scroll"
authors = ["ktiays <cuansky@gmail.com>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
ffi = []

[lib]
crate-type = ["rlib", "staticlib"]

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = true
